name: Create custom attestation type

on:
  workflow_dispatch:

env:
  KOSLI_ORG: cyber-dojo  # Org name in https://app.kosli.com
  KOSLI_HOST: ${{ vars.KOSLI_HOST }}
  KOSLI_API_TOKEN: '${{ secrets.KOSLI_API_TOKEN }}'

jobs:
  create-custom-attestation-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create secrets attestation type
        if: ${{ github.ref == 'refs/heads/main' }}
        run:
          kosli create attestation-type secrets
            --description "Existence of secret .txt file, existence of secret in Github, days to expiry"
            --jq "[.[] | .is_secret == false or (.has_txt_file and .days_to_expiry >= 7 and .has_github_secret and .days_since_update <= (365-7))] | all"
            --schema "./docs/custom-attestation-type-schema.json"
